inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-sorbet

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - sorbet/**/*.rbi

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Exclude:
    - lib/typed/http/status_code.rb

Metrics/BlockLength:
  Exclude:
    - lib/typed/http/status_code.rb

Metrics/ClassLength:
  Exclude:
    - lib/typed/http/status_code.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/typed/http/status_code.rb

Metrics/MethodLength:
  Exclude:
    - lib/typed/http/status_code.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/typed/http/status_code.rb

Style/AccessorGrouping:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
